config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cars#index"
  resources :cars do
    resources :comments, only: :create
  end
  resources :users, only: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord

  with_options presence: true do
    validates :car_name
    validates :text
  end

  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :barth_day
  end

  has_many :cars
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :barth_day])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_car, only: [:edit, :show, :destroy, :update]
  before_action :move_to_index, only: [:edit, :update]

  def index
    @cars = Car.all.order(created_at: 'desc')
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @car.comments.includes(:user)
  end

  def destroy
    if @car.user_id == current_user.id
      redirect_to root_path if @car.destroy
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def car_params
    params.require(:car).permit(:car_name, :text, :image).merge(user_id: current_user.id)
  end

  def set_car
    @car = Car.find(params[:id])
  end

  def move_to_index
    redirect_to cars_path unless @car.user_id == current_user.id
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/cars/#{comment.car.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, car_id: params[:car_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @cars = current_user.cars
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/edit.html.erb
<div class="contents row">
  <div class="containers">
    <h3>編集する</h3>
    <%= form_with model: @car, local: true do |f| %>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">車の名前</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :car_name, class:"input-default", id:"car_name", placeholder:"車種" %>
      </div>
      </div class="form-group">
        <div class="form-text-wrap">
          <label class="form-text">画像</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.file_field :image, class:"input-default", id:"image"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">text</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"input-default", id:"text", placeholder:"こだわりポイント" %>
      </div>
      <div class="actions">
        <%= f.submit "編集する" %>
      </div>
    <% end %>
  </div>
</div>

app/views/cars/index.html.erb
<h1>投稿一覧</h1>
<div class="content">
  <div class="contents">
    <% @cars.each do |car| %>
      <h2 class="car-name"><%= car.car_name %></h2>
      <h2 class="car-text"><%= car.text %></h2>
      <%= link_to car_path(car.id), method: :get do%>
      <div class="car-image">
        <%= image_tag car.image, class: "car-image" if car.image.attached? %>
      </div>
      <% end%>
    <% end %>
  </div>
</div>

app/views/cars/new.html.erb
<div class="contents row">
  <div class="containers">
    <h3>投稿する</h3>
    <%= form_with model: @car, local: true do |f| %>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">車の名前</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :car_name, class:"input-default", id:"car_name", placeholder:"車種" %>
      </div>
      </div class="form-group">
        <div class="form-text-wrap">
          <label class="form-text">画像</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.file_field :image, class:"input-default", id:"image"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">text</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"input-default", id:"text", placeholder:"こだわりポイント" %>
      </div>
      <div class="actions">
        <%= f.submit "新規投稿" %>
      </div>
    <% end %>
  </div>
</div>

app/views/cars/show.html.erb
<div class="car-show">
  <div class="car-box">
    <h2 class="car-name">
      <%= @car.car_name%>
    </h2>
    <div class="text">
      <h2 class="car-text">
        <%= @car.text%>
      </h2>
    </div>
    <%= image_tag @car.image, class: "show-image" if @car.image.attached? %>
  </div>
  
  <div class="edit">
    <%if user_signed_in?%>
      <%if current_user.id == @car.user_id%>
      <%= link_to "商品の編集", edit_car_path(@car.id), method: :get, class: "car-edit" %> 
      <%= link_to "削除", car_path(@car.id), method: :delete, class: "car-destroy" %>
      <%end%>
    <%end%>
  </div>

  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@car, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "送信" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%=comment.user.nickname%></strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LikeCar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="header">
    <div class="header_bar">
      <h1 class="right-head">LikeCar</h1>
      <% if user_signed_in?%>
        <div class="user">
          <span><%= current_user.nickname%>
            <ul class="users">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}"%>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete%>
              </li>
            </ul>
          </span>
          <%= link_to "投稿する", new_car_path, class: "post"%>
        </div>
      <% else%>
        <div class="user">
          <%= link_to "ログイン", new_user_session_path, class: "post"%>
          <%= link_to "新規登録", new_user_registration_path, class: "post"%>
        </div>
      <%end%>
    </div>
  </header>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="car-show">
  <div class="car-box">
    <h1><%= @nickname %>さんの投稿一覧</h1>
    <% @cars.each do |car| %>
      <h2 class="car-text"><%= car.text %></h2>
      <h2 class="car-name"><%= car.car_name %></h2>
      <%= image_tag car.image, class: "show-image"%>
    <% end %>
</div>